#ifndef RAPIDVULKAN_DEBUG_STRINGS_VKSTRUCTURETYPE_HPP
#define RAPIDVULKAN_DEBUG_STRINGS_VKSTRUCTURETYPE_HPP
//***************************************************************************************************************************************************
//* BSD 3-Clause License
//*
//* Copyright (c) 2017, Rene Thrane
//* All rights reserved.
//*
//* Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//*
//* 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
//* 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
//*    documentation and/or other materials provided with the distribution.
//* 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this
//*    software without specific prior written permission.
//*
//* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
//* THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
//* CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
//* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//* LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
//* EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//***************************************************************************************************************************************************

// If you use the functionality in this file its recommended to 'WRAP' it in a hpp/cpp file combo so its only included in one file!

// Auto-generated Vulkan 1.0 C++11 RAII classes by RAIIGen (https://github.com/Unarmed1000/RAIIGen)

#include <vulkan/vulkan.h>

namespace RapidVulkan
{
  namespace Debug
  {
    inline const char* TryToString(const VkStructureType& value)
    {
      switch(value)
      {
      case VK_STRUCTURE_TYPE_APPLICATION_INFO:
        return "VK_STRUCTURE_TYPE_APPLICATION_INFO";
      case VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_SUBMIT_INFO";
      case VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO";
      case VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE:
        return "VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE";
      case VK_STRUCTURE_TYPE_BIND_SPARSE_INFO:
        return "VK_STRUCTURE_TYPE_BIND_SPARSE_INFO";
      case VK_STRUCTURE_TYPE_FENCE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_FENCE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_EVENT_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_EVENT_CREATE_INFO";
      case VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO";
      case VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO";
      case VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO";
      case VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO";
      case VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO";
      case VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO";
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO";
      case VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO";
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO";
      case VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET:
        return "VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET";
      case VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET:
        return "VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET";
      case VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO";
      case VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO";
      case VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO";
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO";
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO";
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO";
      case VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO";
      case VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER:
        return "VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER";
      case VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER:
        return "VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER";
      case VK_STRUCTURE_TYPE_MEMORY_BARRIER:
        return "VK_STRUCTURE_TYPE_MEMORY_BARRIER";
      case VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO";
      case VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO";
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO:
        return "VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO:
        return "VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS:
        return "VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO:
        return "VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO:
        return "VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO:
        return "VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2:
        return "VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2:
        return "VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2:
        return "VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2:
        return "VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2:
        return "VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2:
        return "VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 106
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTERS_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTERS_FEATURES";
#elif VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES";
#endif

#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2:
        return "VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO:
        return "VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO:
        return "VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES:
        return "VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES:
        return "VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES:
        return "VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES:
        return "VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES:
        return "VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT";
#endif
#if VK_HEADER_VERSION >= 106
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETERS_FEATURES";
#elif VK_HEADER_VERSION >= 70
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES";
#endif

#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_1_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2:
        return "VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_2";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2:
        return "VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_2";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2:
        return "VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_2";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2:
        return "VK_STRUCTURE_TYPE_SUBPASS_DEPENDENCY_2";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_SUBPASS_BEGIN_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SUBPASS_END_INFO:
        return "VK_STRUCTURE_TYPE_SUBPASS_END_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_8BIT_STORAGE_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DRIVER_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_FLOAT16_INT8_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FLOAT_CONTROLS_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DEPTH_STENCIL_RESOLVE_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE:
        return "VK_STRUCTURE_TYPE_SUBPASS_DESCRIPTION_DEPTH_STENCIL_RESOLVE";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_MEMORY_MODEL_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGELESS_FRAMEBUFFER_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGELESS_FRAMEBUFFER_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO:
        return "VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_ATTACHMENT_BEGIN_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_UNIFORM_BUFFER_STANDARD_LAYOUT_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_SUBGROUP_EXTENDED_TYPES_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SEPARATE_DEPTH_STENCIL_LAYOUTS_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SEPARATE_DEPTH_STENCIL_LAYOUTS_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_STENCIL_LAYOUT:
        return "VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_STENCIL_LAYOUT";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_STENCIL_LAYOUT:
        return "VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_STENCIL_LAYOUT";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_HOST_QUERY_RESET_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TIMELINE_SEMAPHORE_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_TYPE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_TIMELINE_SEMAPHORE_SUBMIT_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_WAIT_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO:
        return "VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_MEMORY_OPAQUE_CAPTURE_ADDRESS_ALLOCATE_INFO:
        return "VK_STRUCTURE_TYPE_MEMORY_OPAQUE_CAPTURE_ADDRESS_ALLOCATE_INFO";
#endif
#if VK_HEADER_VERSION >= 131
      case VK_STRUCTURE_TYPE_DEVICE_MEMORY_OPAQUE_CAPTURE_ADDRESS_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_MEMORY_OPAQUE_CAPTURE_ADDRESS_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_3_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PIPELINE_CREATION_FEEDBACK_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_CREATION_FEEDBACK_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TERMINATE_INVOCATION_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_TERMINATE_INVOCATION_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TOOL_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TOOL_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DEMOTE_TO_HELPER_INVOCATION_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRIVATE_DATA_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PRIVATE_DATA_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_DEVICE_PRIVATE_DATA_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DEVICE_PRIVATE_DATA_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PRIVATE_DATA_SLOT_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PIPELINE_CREATION_CACHE_CONTROL_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_MEMORY_BARRIER_2:
        return "VK_STRUCTURE_TYPE_MEMORY_BARRIER_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2:
        return "VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2:
        return "VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_DEPENDENCY_INFO:
        return "VK_STRUCTURE_TYPE_DEPENDENCY_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_SUBMIT_INFO_2:
        return "VK_STRUCTURE_TYPE_SUBMIT_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_SUBMIT_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SYNCHRONIZATION_2_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_WORKGROUP_MEMORY_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ZERO_INITIALIZE_WORKGROUP_MEMORY_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ROBUSTNESS_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_ROBUSTNESS_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COPY_BUFFER_INFO_2:
        return "VK_STRUCTURE_TYPE_COPY_BUFFER_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COPY_IMAGE_INFO_2:
        return "VK_STRUCTURE_TYPE_COPY_IMAGE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COPY_BUFFER_TO_IMAGE_INFO_2:
        return "VK_STRUCTURE_TYPE_COPY_BUFFER_TO_IMAGE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COPY_IMAGE_TO_BUFFER_INFO_2:
        return "VK_STRUCTURE_TYPE_COPY_IMAGE_TO_BUFFER_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2:
        return "VK_STRUCTURE_TYPE_BLIT_IMAGE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_RESOLVE_IMAGE_INFO_2:
        return "VK_STRUCTURE_TYPE_RESOLVE_IMAGE_INFO_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_BUFFER_COPY_2:
        return "VK_STRUCTURE_TYPE_BUFFER_COPY_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_IMAGE_COPY_2:
        return "VK_STRUCTURE_TYPE_IMAGE_COPY_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_IMAGE_BLIT_2:
        return "VK_STRUCTURE_TYPE_IMAGE_BLIT_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_BUFFER_IMAGE_COPY_2:
        return "VK_STRUCTURE_TYPE_BUFFER_IMAGE_COPY_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_IMAGE_RESOLVE_2:
        return "VK_STRUCTURE_TYPE_IMAGE_RESOLVE_2";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_REQUIRED_SUBGROUP_SIZE_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_SIZE_CONTROL_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INLINE_UNIFORM_BLOCK_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK:
        return "VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_INLINE_UNIFORM_BLOCK";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXTURE_COMPRESSION_ASTC_HDR_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXTURE_COMPRESSION_ASTC_HDR_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_RENDERING_INFO:
        return "VK_STRUCTURE_TYPE_RENDERING_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO:
        return "VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO:
        return "VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DYNAMIC_RENDERING_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDERING_INFO:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDERING_INFO";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_INTEGER_DOT_PRODUCT_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TEXEL_BUFFER_ALIGNMENT_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3:
        return "VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_3";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_FEATURES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_4_PROPERTIES";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS:
        return "VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS:
        return "VK_STRUCTURE_TYPE_DEVICE_IMAGE_MEMORY_REQUIREMENTS";
#endif
#if VK_HEADER_VERSION >= 106
      case VK_STRUCTURE_TYPE_STREAM_DESCRIPTOR_SURFACE_CREATE_INFO_GGP:
        return "VK_STRUCTURE_TYPE_STREAM_DESCRIPTOR_SURFACE_CREATE_INFO_GGP";
#endif
#if VK_HEADER_VERSION >= 39
      case VK_STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN:
        return "VK_STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN";
#endif
#if VK_HEADER_VERSION >= 42
      case VK_STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK:
        return "VK_STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK";
#endif
#if VK_HEADER_VERSION >= 42
      case VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK:
        return "VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID:
        return "VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID:
        return "VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID:
        return "VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID:
        return "VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID:
        return "VK_STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID";
#endif
#if VK_HEADER_VERSION >= 73
      case VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID:
        return "VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_2_ANDROID:
        return "VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_2_ANDROID";
#endif
#if VK_HEADER_VERSION >= 106
      case VK_STRUCTURE_TYPE_PRESENT_FRAME_TOKEN_GGP:
        return "VK_STRUCTURE_TYPE_PRESENT_FRAME_TOKEN_GGP";
#endif
#if VK_HEADER_VERSION >= 92
      case VK_STRUCTURE_TYPE_IMAGEPIPE_SURFACE_CREATE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMAGEPIPE_SURFACE_CREATE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 135
      case VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDER_PASS_TRANSFORM_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_RENDER_PASS_TRANSFORM_INFO_QCOM";
#endif
#if VK_HEADER_VERSION >= 135
      case VK_STRUCTURE_TYPE_RENDER_PASS_TRANSFORM_BEGIN_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_RENDER_PASS_TRANSFORM_BEGIN_INFO_QCOM";
#endif
#if VK_HEADER_VERSION >= 162
      case VK_STRUCTURE_TYPE_COPY_COMMAND_TRANSFORM_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_COPY_COMMAND_TRANSFORM_INFO_QCOM";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_IMPORT_MEMORY_ZIRCON_HANDLE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMPORT_MEMORY_ZIRCON_HANDLE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_MEMORY_ZIRCON_HANDLE_PROPERTIES_FUCHSIA:
        return "VK_STRUCTURE_TYPE_MEMORY_ZIRCON_HANDLE_PROPERTIES_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_MEMORY_GET_ZIRCON_HANDLE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_MEMORY_GET_ZIRCON_HANDLE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_ZIRCON_HANDLE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_ZIRCON_HANDLE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_SEMAPHORE_GET_ZIRCON_HANDLE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_SEMAPHORE_GET_ZIRCON_HANDLE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_COLLECTION_CREATE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_COLLECTION_CREATE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_IMPORT_MEMORY_BUFFER_COLLECTION_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMPORT_MEMORY_BUFFER_COLLECTION_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_COLLECTION_IMAGE_CREATE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_COLLECTION_IMAGE_CREATE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_COLLECTION_PROPERTIES_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_COLLECTION_PROPERTIES_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_CONSTRAINTS_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_CONSTRAINTS_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_COLLECTION_BUFFER_CREATE_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_COLLECTION_BUFFER_CREATE_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_IMAGE_CONSTRAINTS_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMAGE_CONSTRAINTS_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_IMAGE_FORMAT_CONSTRAINTS_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_IMAGE_FORMAT_CONSTRAINTS_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_SYSMEM_COLOR_SPACE_FUCHSIA:
        return "VK_STRUCTURE_TYPE_SYSMEM_COLOR_SPACE_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 198
      case VK_STRUCTURE_TYPE_BUFFER_COLLECTION_CONSTRAINTS_INFO_FUCHSIA:
        return "VK_STRUCTURE_TYPE_BUFFER_COLLECTION_CONSTRAINTS_INFO_FUCHSIA";
#endif
#if VK_HEADER_VERSION >= 189
      case VK_STRUCTURE_TYPE_SUBPASS_SHADING_PIPELINE_CREATE_INFO_HUAWEI:
        return "VK_STRUCTURE_TYPE_SUBPASS_SHADING_PIPELINE_CREATE_INFO_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 189
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_SHADING_FEATURES_HUAWEI:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_SHADING_FEATURES_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 189
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_SHADING_PROPERTIES_HUAWEI:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBPASS_SHADING_PROPERTIES_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 189
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INVOCATION_MASK_FEATURES_HUAWEI:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_INVOCATION_MASK_FEATURES_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 176
      case VK_STRUCTURE_TYPE_SCREEN_SURFACE_CREATE_INFO_QNX:
        return "VK_STRUCTURE_TYPE_SCREEN_SURFACE_CREATE_INFO_QNX";
#endif
#if VK_HEADER_VERSION >= 239
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_FEATURES_HUAWEI:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_FEATURES_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 239
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_PROPERTIES_HUAWEI:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CLUSTER_CULLING_SHADER_PROPERTIES_HUAWEI";
#endif
#if VK_HEADER_VERSION >= 243
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_ARM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_ARM";
#endif
#if VK_HEADER_VERSION >= 211
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_SET_HOST_MAPPING_FEATURES_VALVE:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_SET_HOST_MAPPING_FEATURES_VALVE";
#endif
#if VK_HEADER_VERSION >= 211
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_BINDING_REFERENCE_VALVE:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_BINDING_REFERENCE_VALVE";
#endif
#if VK_HEADER_VERSION >= 211
      case VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_HOST_MAPPING_INFO_VALVE:
        return "VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_HOST_MAPPING_INFO_VALVE";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_FEATURES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_FEATURES_QCOM";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_PROPERTIES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FRAGMENT_DENSITY_MAP_OFFSET_PROPERTIES_QCOM";
#endif
#if VK_HEADER_VERSION >= 204
      case VK_STRUCTURE_TYPE_SUBPASS_FRAGMENT_DENSITY_MAP_OFFSET_END_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_SUBPASS_FRAGMENT_DENSITY_MAP_OFFSET_END_INFO_QCOM";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_FEATURES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_FEATURES_QCOM";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_PROPERTIES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_PROCESSING_PROPERTIES_QCOM";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_IMAGE_VIEW_SAMPLE_WEIGHT_CREATE_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_IMAGE_VIEW_SAMPLE_WEIGHT_CREATE_INFO_QCOM";
#endif
#if VK_HEADER_VERSION >= 236
      case VK_STRUCTURE_TYPE_DIRECT_DRIVER_LOADING_INFO_LUNARG:
        return "VK_STRUCTURE_TYPE_DIRECT_DRIVER_LOADING_INFO_LUNARG";
#endif
#if VK_HEADER_VERSION >= 236
      case VK_STRUCTURE_TYPE_DIRECT_DRIVER_LOADING_LIST_LUNARG:
        return "VK_STRUCTURE_TYPE_DIRECT_DRIVER_LOADING_LIST_LUNARG";
#endif
#if VK_HEADER_VERSION >= 231
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_EXT:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_RASTERIZATION_ORDER_ATTACHMENT_ACCESS_FEATURES_EXT";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_PROPERTIES_FEATURES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_TILE_PROPERTIES_FEATURES_QCOM";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_TILE_PROPERTIES_QCOM:
        return "VK_STRUCTURE_TYPE_TILE_PROPERTIES_QCOM";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_AMIGO_PROFILING_FEATURES_SEC:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_AMIGO_PROFILING_FEATURES_SEC";
#endif
#if VK_HEADER_VERSION >= 224
      case VK_STRUCTURE_TYPE_AMIGO_PROFILING_SUBMIT_INFO_SEC:
        return "VK_STRUCTURE_TYPE_AMIGO_PROFILING_SUBMIT_INFO_SEC";
#endif
#if VK_HEADER_VERSION >= 236
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_VIEWPORTS_FEATURES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_VIEWPORTS_FEATURES_QCOM";
#endif
#if VK_HEADER_VERSION >= 231
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MUTABLE_DESCRIPTOR_TYPE_FEATURES_EXT";
#endif
#if VK_HEADER_VERSION >= 231
      case VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT:
        return "VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT";
#endif
#if VK_HEADER_VERSION >= 231
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_FEATURES_ARM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_FEATURES_ARM";
#endif
#if VK_HEADER_VERSION >= 231
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_BUILTINS_PROPERTIES_ARM";
#endif
#if VK_HEADER_VERSION >= 243
      case VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_RENDER_AREAS_FEATURES_QCOM:
        return "VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_RENDER_AREAS_FEATURES_QCOM";
#endif
#if VK_HEADER_VERSION >= 243
      case VK_STRUCTURE_TYPE_MULTIVIEW_PER_VIEW_RENDER_AREAS_RENDER_PASS_BEGIN_INFO_QCOM:
        return "VK_STRUCTURE_TYPE_MULTIVIEW_PER_VIEW_RENDER_AREAS_RENDER_PASS_BEGIN_INFO_QCOM";
#endif
      default:
        return nullptr;
      }
    };

    inline const char* ToString(const VkStructureType& value)
    {
      auto result = TryToString(value);
      return (result != nullptr ? result : "*Unknown*");
    };
  }
}

#endif
